name: easy_locate
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.1
  localregex: ^0.0.1
  modal_progress_hud: ^0.1.3
  shared_preferences: ^0.5.7+3
  provider: ^4.1.3
  flutter_easyloading: ^1.0.1
  corsac_jwt: ^0.2.2
  jwt_decode: ^0.1.0
  jwt_decoder: ^1.0.1
  jaguar_jwt: ^2.1.6
  geolocator: ^5.3.2+2
  toast: ^0.1.5
  shimmer: ^1.1.1
  carousel_pro: ^1.0.0
  google_maps_flutter: ^0.5.28+1
  permission_handler: ^5.0.1+1
  badges: ^1.1.1
  location: ^3.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf