name: easy_locate
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.1
  shared_preferences: ^0.5.7+3
  provider: ^4.1.3
  flutter_easyloading: ^1.0.1
  flutter_progress_hud: ^1.0.2
  corsac_jwt: ^0.2.2
  jwt_decode: ^0.1.0
  jwt_decoder: ^1.0.1
  jaguar_jwt: ^2.1.6
  fluttertoast: any
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf